trigger:
- main

strategy:
  matrix:
    linux:
      operatingSystem: 'ubuntu-latest'
    mac:
      operatingSystem: 'macos-latest'

pool:
  vmImage: $(opertaingsystem)

steps:
- script: echo Running on the Operating system!
  displayName: 'Run a one-line script'

